#define ALIENOS_KEY_UP 0x80
#define ALIENOS_KEY_LEFT 0x81
#define ALIENOS_KEY_DOWN 0x82
#define ALIENOS_KEY_RIGHT 0x83

#define ALIENOS_END 0
#define ALIENOS_GETRAND 1
#define ALIENOS_GETKEY 2
#define ALIENOS_PRINT 3
#define ALIENOS_SETCURSOR 4

#define PT_PARAMS 0x60031337

#define FAILURE_CODE 127